// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByOWBYabIpzqMRlI74BeIelEL1WyEDty8',
    appId: '1:38743626366:web:40afdd9b74b77b6b55be2f',
    messagingSenderId: '38743626366',
    projectId: 'd5n-interview-7ac5f',
    authDomain: 'd5n-interview-7ac5f.firebaseapp.com',
    storageBucket: 'd5n-interview-7ac5f.appspot.com',
    measurementId: 'G-XSD956Z264',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfciZmpKGO5RWflhjjHWsgnHvo3ApVgNQ',
    appId: '1:38743626366:android:eeea6be7e0cbe42655be2f',
    messagingSenderId: '38743626366',
    projectId: 'd5n-interview-7ac5f',
    storageBucket: 'd5n-interview-7ac5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYMx4Fm7TSJ6u8P3mnpRKhJLFh1mviaao',
    appId: '1:38743626366:ios:f11922bc94b2450955be2f',
    messagingSenderId: '38743626366',
    projectId: 'd5n-interview-7ac5f',
    storageBucket: 'd5n-interview-7ac5f.appspot.com',
    iosBundleId: 'com.example.d5nInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYMx4Fm7TSJ6u8P3mnpRKhJLFh1mviaao',
    appId: '1:38743626366:ios:f11922bc94b2450955be2f',
    messagingSenderId: '38743626366',
    projectId: 'd5n-interview-7ac5f',
    storageBucket: 'd5n-interview-7ac5f.appspot.com',
    iosBundleId: 'com.example.d5nInterview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByOWBYabIpzqMRlI74BeIelEL1WyEDty8',
    appId: '1:38743626366:web:626bcdff687b9bc555be2f',
    messagingSenderId: '38743626366',
    projectId: 'd5n-interview-7ac5f',
    authDomain: 'd5n-interview-7ac5f.firebaseapp.com',
    storageBucket: 'd5n-interview-7ac5f.appspot.com',
    measurementId: 'G-Q4XQWH2YT3',
  );
}
